const assert = require('node:assert/strict');
const { createHash } = require('node:crypto');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
let pw;
try { pw = require('playwright'); } catch { pw = require(path.join(process.env.USERPROFILE, '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')); }
const digest = text => createHash('sha256').update(text, 'utf8').digest('hex');
(async () => {
  const browser = await pw.chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1366, height: 768 }, reducedMotion: 'no-preference' });
  const errors = [], networkRequests = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', r => { if (/^https?:/.test(r.url())) networkRequests.push(r.url()); });
  await page.goto(pathToFileURL(path.resolve(__dirname, '../apresentacao.html')).href);
  const go = async id => {
    await page.evaluate(id => { const slides = [...document.querySelectorAll('.slide')]; location.hash = String(slides.indexOf(document.getElementById(id)) + 1); }, id);
    await page.waitForFunction(id => document.getElementById(id).classList.contains('active'), id);
  };
  const fits = async () => { const result = await page.locator('.slide.active').evaluate(s => ({ id: s.id, scroll: s.scrollHeight, height: s.clientHeight })); assert(result.scroll <= result.height + 2, JSON.stringify(result)); };
  await go('problem-slide');
  assert.equal(await page.locator('#problem-slide .concept-grid article').count(), 3);
  assert.equal(await page.locator('#problem-slide button').count(), 0); await fits();
  await go('history-slide');
  assert.equal(await page.locator('#history-slide .milestones article').count(), 5);
  assert.equal(await page.locator('#history-slide button').count(), 0); await fits();
  const animated = page.locator('#history-slide .ambient-block').first();
  assert.equal(await animated.evaluate(e => getComputedStyle(e).animationPlayState), 'running');
  await page.locator('#motion-toggle').click(); assert.equal(await animated.evaluate(e => getComputedStyle(e).animationPlayState), 'paused');
  await page.locator('#motion-toggle').click(); assert.equal(await animated.evaluate(e => getComputedStyle(e).animationPlayState), 'running');
  await page.emulateMedia({ reducedMotion: 'reduce' }); await page.waitForFunction(() => document.querySelector('#motion-toggle').disabled); assert.equal(await animated.evaluate(e => getComputedStyle(e).animationName), 'none');
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await go('hash-slide');
  for (const input of ['abc', '', 'Olá 🔐\nUTF-8', '<img src=x onerror=alert(1)>']) {
    await page.locator('#hash-input').fill(input);
    await page.waitForFunction(expected => document.querySelector('#hash-output-b').textContent === expected, digest(input));
    assert.equal(await page.locator('#hash-output-b img').count(), 0);
  }
  await page.locator('#hash-reference').fill('abc'); await page.locator('#hash-match').click();
  await page.waitForFunction(() => document.querySelector('#hash-bit-count').textContent === '0');
  await page.locator('#hash-space').click(); await page.waitForFunction(expected => document.querySelector('#hash-output-b').textContent === expected, digest('abc '));
  const xorBits = [...digest('abc')].reduce((sum, c, i) => sum + (parseInt(c, 16) ^ parseInt(digest('abc ')[i], 16)).toString(2).replace(/0/g, '').length, 0);
  assert.equal(Number(await page.locator('#hash-bit-count').innerText()), xorBits);
  await page.locator('#hash-input').fill('a'.repeat(1000)); await page.locator('#hash-space').click(); assert.equal((await page.locator('#hash-input').inputValue()).length, 1000);
  await page.locator('#hash-reset').click(); await fits();
  await go('chain-slide'); await page.waitForFunction(() => !document.querySelector('#chain-data-0').disabled);
  const originalHashes = await page.locator('.current-hash').evaluateAll(nodes => nodes.map(n => n.title));
  assert.equal(originalHashes[0], digest(JSON.stringify([1, '0'.repeat(64), 'Alice envia 10 para Bob'])));

  await page.locator('#chain-data-0').fill('Alice envia 100 para Bob');
  await page.waitForFunction(() => document.querySelectorAll('.modified').length === 3);
  assert.equal(await page.locator('.bad-link').count(), 0); await fits();
  const changedHashes = await page.locator('.current-hash').evaluateAll(nodes => nodes.map(n => n.title));
  assert(changedHashes.every((h, i) => h !== originalHashes[i]));
  for (let i = 0; i < 3; i++) {
    const expected = digest(JSON.stringify([i + 1, i ? changedHashes[i - 1] : '0'.repeat(64), await page.locator('#chain-data-' + i).inputValue()]));
    assert.equal(changedHashes[i], expected);
  }
  await page.locator('.inspect-block').nth(1).click();
  assert(await page.locator('#chain-payload').evaluate(e => e.open));
  assert.equal(digest(await page.locator('#payload-json').innerText()), await page.locator('#payload-hash').innerText());
  await page.keyboard.press('Escape');
  await page.locator('[data-chain-mode=frozen]').click();
  await page.waitForFunction(() => document.querySelectorAll('.bad-link').length === 1);
  assert.equal(await page.locator('.affected').count(), 1);
  assert.deepEqual(await page.locator('.current-hash').evaluateAll(n => n.map(e => e.title).slice(1)), originalHashes.slice(1));
  await page.locator('[data-chain-mode=cascade]').click();
  await page.waitForFunction(() => document.querySelectorAll('.modified').length === 3);
  await page.locator('#chain-reset').click();
  await page.waitForFunction(() => document.querySelectorAll('.modified').length === 0);
  assert.deepEqual(await page.locator('.current-hash').evaluateAll(n => n.map(e => e.title)), originalHashes);
  await page.locator('#chain-data-1').fill('Olá 🔐 <img src=x>');
  await page.waitForFunction(() => document.querySelectorAll('.modified').length === 2);
  assert.equal(await page.locator('.current-hash').first().innerText(), originalHashes[0]);
  await page.locator('.inspect-block').nth(1).click();
  assert.equal(await page.locator('#payload-json img').count(), 0);
  assert.equal(digest(await page.locator('#payload-json').innerText()), await page.locator('#payload-hash').innerText());
  await page.keyboard.press('Escape');
  await page.locator('#chain-reset').click(); await page.waitForFunction(() => document.querySelectorAll('.modified').length === 0);
  await page.locator('#chain-data-2').fill('Último'); await page.waitForFunction(() => document.querySelectorAll('.modified').length === 1);
  await go('pow-slide');
  for (const invalid of ['-1', '1.5', '+1', 'abc', '']) {
    await page.locator('#pow-nonce').fill(invalid); await page.locator('#pow-test').click();
    assert.match(await page.locator('#pow-status').innerText(), /inteiro/);
    assert.equal(await page.locator('#pow-attempts').innerText(), '0');
  }
  await page.locator('#pow-nonce').fill('42');
  assert.equal(await page.locator('#pow-hash').innerText(), '—');
  await page.locator('#pow-test').click();
  await page.waitForFunction(expected => document.querySelector('#pow-hash').textContent === expected, digest(JSON.stringify(['Bloco de demonstração', 42])));
  await page.locator('#pow-test').click(); await page.waitForFunction(() => document.querySelector('#pow-attempts').textContent === '2');
  await page.locator('#pow-increment').click(); await page.waitForFunction(expected => document.querySelector('#pow-hash').textContent === expected, digest(JSON.stringify(['Bloco de demonstração', 43])));
  const hugeNonce = '999999999999999999999999999999';
  await page.locator('#pow-nonce').fill(hugeNonce); await page.locator('#pow-test').click();
  await page.waitForFunction(expected => document.querySelector('#pow-hash').textContent === expected, digest(`["Bloco de demonstração",${hugeNonce}]`));
  await page.locator('#pow-increment').click();
  await page.waitForFunction(expected => document.querySelector('#pow-hash').textContent === expected, digest('["Bloco de demonstração",1000000000000000000000000000000]'));
  await page.locator('#pow-clear').click(); assert.equal(await page.locator('#pow-attempts').innerText(), '0');
  assert.equal(await page.locator('#pow-rate').innerText(), '—');
  await page.locator('#pow-difficulty').fill('5'); assert.equal(await page.locator('#pow-expected').innerText(), '1.048.576');
  await page.locator('#pow-difficulty').fill('65'); assert.match(await page.locator('#pow-status').innerText(), /entre 0 e 64/);
  await page.locator('#pow-nonce').fill('0'); await page.locator('#pow-difficulty').fill('2');
  await page.locator('#pow-mine').click(); await page.waitForFunction(() => !document.querySelector('#pow-mine').disabled, null, { timeout: 20000 });
  const nonce = Number(await page.locator('#pow-nonce').inputValue());
  const powHash = digest(JSON.stringify(['Bloco de demonstração', nonce]));
  assert(powHash.startsWith('00')); assert.equal(await page.locator('#pow-hash').innerText(), powHash);
  assert.match(await page.locator('#pow-rate').innerText(), /h\/s/); await fits();
  await page.locator('#pow-data').fill('Dado adulterado'); assert.equal(await page.locator('#pow-attempts').innerText(), '0');
  await page.locator('#pow-test').click(); await page.waitForFunction(expected => document.querySelector('#pow-hash').textContent === expected, digest(JSON.stringify(['Dado adulterado', nonce])));
  await page.locator('#pow-difficulty').fill('4'); await page.locator('#pow-nonce').fill('0');
  await page.locator('#pow-mine').click(); await page.locator('#pow-stop').click(); assert.match(await page.locator('#pow-status').innerText(), /parada/);
  const stoppedCount = await page.locator('#pow-attempts').innerText(); await page.waitForTimeout(350); assert.equal(await page.locator('#pow-attempts').innerText(), stoppedCount);
  await page.locator('#pow-nonce').fill('0'); await page.locator('#pow-difficulty').fill('4');
  await page.locator('#pow-mine').click(); await go('flow-slide'); assert(await page.locator('#pow-mine').isEnabled());
  await go('btc-schema-slide');
  assert.equal(await page.locator('#btc-schema-slide .btc-schema-block').count(), 3);
  assert.deepEqual(await page.locator('#btc-schema-slide .btc-schema-block dl').evaluateAll(lists => lists.map(list => list.children.length)), [6, 6, 6]);
  assert.equal(await page.locator('#btc-schema-slide .btc-schema-block').nth(1).locator('.linked dd').innerText(), await page.locator('#btc-schema-slide .btc-schema-block').nth(0).locator('.btc-block-hash code').innerText()); await fits();
  await go('flow-slide');
  assert.equal(await page.locator('#flow-slide .flow-stages article').count(), 5);
  assert.equal(await page.locator('#flow-slide button').count(), 0); await fits();
  await go('pos-slide');
  for (const [id, value] of [['#stake-0', '100'], ['#stake-1', '0'], ['#stake-2', '0'], ['#stake-3', '0']]) await page.locator(id).fill(value);
  assert.equal(await page.locator('.stake-row').first().locator('.stake-share').innerText(), '100%');
  await page.locator('#stake-draw').click();
  assert.equal(await page.locator('.stake-row.picked .stake-name').innerText(), 'Ana');
  assert.match(await page.locator('#stake-result').innerText(), /Ana · rodada 1/);
  await page.locator('#stake-run').click();
  assert.match(await page.locator('#stake-result').innerText(), /201 rodadas/);
  assert.equal(await page.locator('.stake-row').first().locator('.stake-turns').innerText(), '100%');
  assert.equal(await page.locator('.stake-row').nth(1).locator('.stake-turns').innerText(), '0%');
  await page.locator('#stake-0').fill('0'); assert.equal(await page.locator('.stake-row').first().locator('.stake-turns').innerText(), '—');
  await page.locator('#stake-draw').click(); assert.match(await page.locator('#stake-result').innerText(), /Defina algum stake/);
  await page.locator('#stake-run').click(); assert.match(await page.locator('#stake-result').innerText(), /Defina algum stake/);
  for (const [id, value] of [['#stake-0', '50'], ['#stake-1', '25'], ['#stake-2', '15'], ['#stake-3', '10']]) await page.locator(id).fill(value);
  await page.locator('#stake-run').click();
  assert.equal(await page.locator('.stake-row.picked').count(), 0);
  await page.locator('#stake-reset').click(); assert.equal(await page.locator('.stake-row').first().locator('.stake-turns').innerText(), '—'); await fits();
  await go('poh-slide');
  await page.waitForFunction(() => document.querySelector('#poh-tick').textContent !== '000000');
  await page.locator('#poh-add').click();
  await page.waitForFunction(() => document.querySelectorAll('#poh-stream .has-tx').length > 0);
  assert((await page.locator('#poh-stream > div').count()) <= 4);
  const tick = await page.locator('#poh-tick').innerText();
  await page.locator('#poh-toggle').click(); await page.waitForTimeout(700);
  assert.equal(await page.locator('#poh-tick').innerText(), tick);
  await page.locator('#poh-toggle').click(); await page.waitForFunction(previous => document.querySelector('#poh-tick').textContent !== previous, tick); await fits();
  await go('networks-slide');
  assert.equal(await page.locator('#networks-slide button').count(), 0);
  assert.match(await page.locator('.network-card.sol').innerText(), /Tower BFT/);
  assert.match(await page.locator('.network-card.sol').innerText(), /Proof of History/);
  assert.match(await page.locator('.network-card.sol').innerText(), /Proof of Stake \+ Proof of History/);
  assert.match(await page.locator('#networks-slide .takeaway').innerText(), /não é consenso/); await fits();
  await go('contract-slide');
  assert.equal(await page.locator('#contract-slide button, #contract-slide input, #contract-slide select').count(), 0);
  assert.equal(await page.locator('#contract-slide .contract-step').count(), 4);
  assert.equal(await page.locator('#contract-slide .contract-guards b').count(), 2);
  assert.match(await page.locator('#contract-slide .contract-guards').innerText(), /REJEITAD/); await fits();
  await page.setViewportSize({ width: 390, height: 844 }); await go('hash-slide'); await page.locator('#hash-input').fill('abc'); await page.waitForFunction(expected => document.querySelector('#hash-output-b').textContent === expected, digest('abc')); assert.equal(await page.locator('#slide-current').innerText(), '25');
  await page.locator('#hash-input').press('ArrowRight'); assert.equal(await page.locator('#slide-current').innerText(), '25');
  await page.locator('body').click({ position: { x: 5, y: 5 } }); await page.keyboard.press('ArrowRight'); assert.equal(await page.locator('#slide-current').innerText(), '26');
  assert.deepEqual(errors, []); assert.deepEqual(networkRequests, []);
  console.log('SHA-256, UTF-8, avalanche, chain tampering, mining cancel, stake lottery, static contract guards, animation controls and offline checks passed.');
  await browser.close();
})().catch(e => { console.error(e); process.exit(1); });
